const summaryContent = {

        introduction: "This chapter introduces students to the basic parts of a sentence. It explains how we express our ideas, feelings and views through sentences, and how a sentence is made up of words joined in a meaningful way. The chapter also teaches the importance of word order in framing correct sentences. (ଏହି ଅଧ୍ୟାୟଟି ଛାତ୍ରମାନଙ୍କୁ ବାକ୍ୟର ମୌଳିକ ଅଂଶଗୁଡ଼ିକ ସହିତ ପରିଚିତ କରାଏ । ଏହା ବୁଝାଏ ଯେ ଆମେ କିପରି ଆମର ଚିନ୍ତାଧାରା, ଅନୁଭବ ଓ ମତାମତ ବାକ୍ୟ ମାଧ୍ୟମରେ ପ୍ରକାଶ କରୁ, ଏବଂ ଏକ ବାକ୍ୟ କିପରି ଶବ୍ଦଗୁଡ଼ିକ ଅର୍ଥପୂର୍ଣ୍ଣ ଭାବେ ମିଶି ଗଠିତ ହୁଏ । ଏହି ଅଧ୍ୟାୟ ମଧ୍ୟ ସଠିକ୍ ବାକ୍ୟ ଗଠନରେ ଶବ୍ଦକ୍ରମର ଗୁରୁତ୍ୱ ଶିଖାଏ ।)",

        sentences: [
            { heading: "Meaning of a Sentence (ବାକ୍ୟର ଅର୍ଥ)", text: "We express our ideas, feelings and views in sentences. A sentence is made up of words and is a meaningful expression. Without proper words joined together correctly, an expression does not become a sentence. (ଆମେ ଆମର ଚିନ୍ତାଧାରା, ଅନୁଭବ ଓ ମତାମତ ବାକ୍ୟରେ ପ୍ରକାଶ କରୁ । ଏକ ବାକ୍ୟ ଶବ୍ଦ ଦ୍ୱାରା ଗଠିତ ଏବଂ ଏହା ଏକ ଅର୍ଥପୂର୍ଣ୍ଣ ଅଭିବ୍ୟକ୍ତି ଅଟେ । ଉପଯୁକ୍ତ ଶବ୍ଦଗୁଡ଼ିକ ସଠିକ୍ ଭାବେ ନ ମିଶିଲେ, ଏକ ଅଭିବ୍ୟକ୍ତି ବାକ୍ୟ ହୋଇପାରେ ନାହିଁ ।)" },

            { heading: "Joining Words to Form Sentences (ବାକ୍ୟ ଗଠନ ପାଇଁ ଶବ୍ଦ ଯୋଡ଼ିବା)", text: "In Activity 1, words from Table A and Table B are joined suitably to make meaningful sentences. For example, 'That boy' is joined with 'is intelligent' to form the sentence 'That boy is intelligent'. Similarly, other words like 'Trees', 'The cows', 'The Chinese' and 'Dilip Tirkey' need to be matched with their correct predicates. (Activity 1 ରେ, Table A ଓ Table B ର ଶବ୍ଦଗୁଡ଼ିକୁ ଉପଯୁକ୍ତ ଭାବେ ଯୋଡ଼ି ଅର୍ଥପୂର୍ଣ୍ଣ ବାକ୍ୟ ତିଆରି କରାଯାଏ । ଉଦାହରଣ ସ୍ୱରୂପ, 'That boy' କୁ 'is intelligent' ସହିତ ଯୋଡ଼ି 'That boy is intelligent' ବାକ୍ୟ ତିଆରି ହୋଇଛି । ସେହିପରି, 'Trees', 'The cows', 'The Chinese' ଓ 'Dilip Tirkey' ଭଳି ଅନ୍ୟ ଶବ୍ଦଗୁଡ଼ିକୁ ମଧ୍ୟ ସେମାନଙ୍କର ସଠିକ୍ predicate ସହିତ ମେଳାଇବାକୁ ପଡ଼ିବ ।)" },

            { heading: "Subject and Predicate (Subject ଓ Predicate)", text: "The parts in column A are called Subjects, and the parts in column B are called Predicates. The Subject tells us who or what the sentence is about, while the Predicate tells us something about the Subject. Every complete sentence must have both a Subject and a Predicate. (ସ୍ତମ୍ଭ A ର ଅଂଶଗୁଡ଼ିକୁ Subject କୁହାଯାଏ, ଏବଂ ସ୍ତମ୍ଭ B ର ଅଂଶଗୁଡ଼ିକୁ Predicate କୁହାଯାଏ । Subject ଆମକୁ କୁହେ ଯେ ବାକ୍ୟଟି କାହା ବିଷୟରେ, ଅନ୍ୟପଟେ Predicate ଆମକୁ Subject ବିଷୟରେ କିଛି କୁହେ । ପ୍ରତ୍ୟେକ ସମ୍ପୂର୍ଣ୍ଣ ବାକ୍ୟରେ Subject ଓ Predicate ଉଭୟ ରହିବା ଆବଶ୍ୟକ ।)" },

            { heading: "Importance of Word Order (ଶବ୍ଦକ୍ରମର ଗୁରୁତ୍ୱ)", text: "Words must be arranged in a particular order or pattern to make a sentence meaningful. 'Indrani is a classical singer' is an acceptable pattern, while 'Classical is Indrani a singer' or 'Singer classical Indrani is a' are not acceptable. This shows that simply having the right words is not enough; their order also matters greatly. (ଏକ ବାକ୍ୟକୁ ଅର୍ଥପୂର୍ଣ୍ଣ କରିବାକୁ ଶବ୍ଦଗୁଡ଼ିକୁ ଏକ ନିର୍ଦ୍ଦିଷ୍ଟ କ୍ରମ କିମ୍ବା ପାଟର୍ନରେ ସଜାଇବାକୁ ପଡ଼େ । 'Indrani is a classical singer' ଏକ ଗ୍ରହଣୀୟ ପାଟର୍ନ, ଅନ୍ୟପଟେ 'Classical is Indrani a singer' କିମ୍ବା 'Singer classical Indrani is a' ଗ୍ରହଣୀୟ ନୁହେଁ । ଏହା ଦର୍ଶାଏ ଯେ କେବଳ ସଠିକ୍ ଶବ୍ଦ ଥିଲେ ହିଁ ଚଳେ ନାହିଁ; ସେମାନଙ୍କର କ୍ରମ ମଧ୍ୟ ବହୁତ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ।)" },

            { heading: "Practicing Word Order (Activity 2 - ଶବ୍ଦକ୍ରମ ଅଭ୍ୟାସ)", text: "In Activity 2, students practice putting jumbled words in the correct order to form meaningful sentences and questions. The first example, 'her / you / waiting / for / are?', is correctly arranged as 'Are you waiting for her?'. This activity helps students understand how changing word order can turn a group of words into a proper statement or question. (Activity 2 ରେ, ଛାତ୍ରମାନେ ଅବ୍ୟବସ୍ଥିତ ଶବ୍ଦଗୁଡ଼ିକୁ ସଠିକ୍ କ୍ରମରେ ସଜାଇ ଅର୍ଥପୂର୍ଣ୍ଣ ବାକ୍ୟ ଓ ପ୍ରଶ୍ନ ତିଆରି କରିବା ଅଭ୍ୟାସ କରନ୍ତି । ପ୍ରଥମ ଉଦାହରଣ, 'her / you / waiting / for / are?', କୁ ସଠିକ୍ ଭାବେ ସଜାଇ 'Are you waiting for her?' ତିଆରି କରାଯାଇଛି । ଏହି କାର୍ଯ୍ୟକଳାପ ଛାତ୍ରମାନଙ୍କୁ ବୁଝାଏ ଯେ ଶବ୍ଦକ୍ରମ ପରିବର୍ତ୍ତନ କରି କିପରି ଏକ ଶବ୍ଦ ଗୋଷ୍ଠୀକୁ ଏକ ସଠିକ୍ ବିବୃତି କିମ୍ବା ପ୍ରଶ୍ନରେ ପରିଣତ କରାଯାଇପାରେ ।)" },

            { heading: "Describing a Person Using Simple Sentences (ସରଳ ବାକ୍ୟ ଦ୍ୱାରା ଜଣେ ବ୍ୟକ୍ତିଙ୍କ ବର୍ଣ୍ଣନା)", text: "The chapter gives an example of simple sentences describing a girl named Itishree. It states that she is in class X, she is fourteen years old, and Mr Karunakar, her father, is an engineer. This example shows how a series of simple Subject-Predicate sentences can together give complete information about a person. (ଅଧ୍ୟାୟଟି ଇତିଶ୍ରୀ ନାମକ ଏକ ବାଳିକାଙ୍କ ବର୍ଣ୍ଣନା କରୁଥିବା ସରଳ ବାକ୍ୟର ଏକ ଉଦାହରଣ ଦିଏ । ଏଥିରେ କୁହାଯାଇଛି ଯେ ସେ ଦଶମ ଶ୍ରେଣୀରେ ପଢ଼ୁଛନ୍ତି, ତାଙ୍କ ବୟସ ଚଉଦ ବର୍ଷ, ଏବଂ ତାଙ୍କ ପିତା ଶ୍ରୀ କରୁଣାକର ଜଣେ ଇଞ୍ଜିନିୟର ଅଟନ୍ତି । ଏହି ଉଦାହରଣ ଦର୍ଶାଏ ଯେ କିପରି ଏକ ପରେ ଏକ ସରଳ Subject-Predicate ବାକ୍ୟଗୁଡ଼ିକ ମିଶି ଜଣେ ବ୍ୟକ୍ତିଙ୍କ ବିଷୟରେ ସମ୍ପୂର୍ଣ୍ଣ ସୂଚନା ଦେଇପାରନ୍ତି ।)" }
        ],

        conclusion: "This chapter helps students understand that a meaningful sentence is formed by correctly joining a Subject with its matching Predicate. It also teaches that the order of words in a sentence is crucial, since the same words arranged differently can make a sentence meaningless or change a statement into a question. Through activities and examples, students learn to build, arrange and use simple sentences correctly. (ଏହି ଅଧ୍ୟାୟ ଛାତ୍ରମାନଙ୍କୁ ବୁଝାଏ ଯେ ଏକ ଅର୍ଥପୂର୍ଣ୍ଣ ବାକ୍ୟ Subject କୁ ତାହାର ମେଳଖାଉଥିବା Predicate ସହିତ ସଠିକ୍ ଭାବେ ଯୋଡ଼ି ତିଆରି ହୁଏ । ଏହା ମଧ୍ୟ ଶିଖାଏ ଯେ ବାକ୍ୟରେ ଶବ୍ଦକ୍ରମ ଅତ୍ୟନ୍ତ ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ, କାରଣ ସମାନ ଶବ୍ଦଗୁଡ଼ିକ ଭିନ୍ନ ଭାବେ ସଜାଗଲେ ବାକ୍ୟଟି ଅର୍ଥହୀନ ହୋଇପାରେ କିମ୍ବା ଏକ ବିବୃତିକୁ ପ୍ରଶ୍ନରେ ପରିଣତ କରିପାରେ । କାର୍ଯ୍ୟକଳାପ ଓ ଉଦାହରଣ ମାଧ୍ୟମରେ, ଛାତ୍ରମାନେ ସରଳ ବାକ୍ୟ ସଠିକ୍ ଭାବେ ଗଠନ, ସଜାଇବା ଓ ବ୍ୟବହାର କରିବା ଶିଖନ୍ତି ।)"
    };
